//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightsEmulator {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlightsEmulator.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to active.
        /// </summary>
        internal static string ActiveStatusMsg {
            get {
                return ResourceManager.GetString("ActiveStatusMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plane is already active.
        /// </summary>
        internal static string AlreadyActiveMsg {
            get {
                return ResourceManager.GetString("AlreadyActiveMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;-help&quot; - prints all available commands.
        /// </summary>
        internal static string HelpCmd {
            get {
                return ResourceManager.GetString("HelpCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;q&quot; - stop app.
        /// </summary>
        internal static string HelpExitCmd {
            get {
                return ResourceManager.GetString("HelpExitCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;locate {id}&quot; - prints current plane location.
        /// </summary>
        internal static string HelpLocationCmd {
            get {
                return ResourceManager.GetString("HelpLocationCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;print {id}&quot; - prints info about all available planes if called without args;   print particular plane info if plane id is entered as argument.
        /// </summary>
        internal static string HelpPrintCmd {
            get {
                return ResourceManager.GetString("HelpPrintCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;status {id}&quot; - prints if particular plane is active or is waiting.
        /// </summary>
        internal static string HelpStatusCmd {
            get {
                return ResourceManager.GetString("HelpStatusCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;start {id}&quot; - starts flight, id - number of plane argument.
        /// </summary>
        internal static string HelpStratCmd {
            get {
                return ResourceManager.GetString("HelpStratCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plane number {0} is active.
        /// </summary>
        internal static string PlaneActiveMsg {
            get {
                return ResourceManager.GetString("PlaneActiveMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plane number: {0}; Current position: lat - {1}, lng - {2}, alt - {3}.
        /// </summary>
        internal static string PlaneCurrentLocationInfo {
            get {
                return ResourceManager.GetString("PlaneCurrentLocationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plane number: {0}; Status: {1}.
        /// </summary>
        internal static string PlaneInfo {
            get {
                return ResourceManager.GetString("PlaneInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plane number {0} is waiting.
        /// </summary>
        internal static string PlaneWaitingMsg {
            get {
                return ResourceManager.GetString("PlaneWaitingMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong, please, make sure you have build FlightDisplay.sln.
        /// </summary>
        internal static string SmthWentWrongMsg {
            get {
                return ResourceManager.GetString("SmthWentWrongMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Plane Flights Emulator program. Please use -help command to see the list of available commands.
        /// </summary>
        internal static string StartMsg {
            get {
                return ResourceManager.GetString("StartMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to waiting.
        /// </summary>
        internal static string WaitingStatusMsg {
            get {
                return ResourceManager.GetString("WaitingStatusMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong command.
        /// </summary>
        internal static string WrongCommandMsg {
            get {
                return ResourceManager.GetString("WrongCommandMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong plane number.
        /// </summary>
        internal static string WrongPlaneNumberdMsg {
            get {
                return ResourceManager.GetString("WrongPlaneNumberdMsg", resourceCulture);
            }
        }
    }
}
